### ISSUE TITLE
Wondering if we could collaborate?

### ISSUE THREAD

**Issue by asottile** [joeyespo/upgrade-requirements.py#1]
It seems like we've written the same project and you may find this useful:

https://github.com/Yelp/requirements-tools#upgrade-requirements

**Comment by joeyespo** [comment]
@ssbarnea Not dead. Just slow to add features.

The error is this line `Error: Can only work with pinned requirements for now.` It might be worth removing the noise of the stack trace in this case. I just opened #6 to help implement this case.

**Comment by joeyespo** [comment]
@asottile Thanks! 😄 

I'd be happy to collaborate. I do intend to keep this a one-off project in the spirit of "do one thing and do it well" though. (Admittedly, it could do that one thing a little better, but that's still easier than making a bigger thing better.) Would you be up for using this as a dependency or submodule of `requirements-tools` at all?

**Comment by asottile** [comment]
I looked through the source and the implementation in requirements-tools has more features and fewer bugs and taking a (significantly less active -- >1 year to respond to issue) dependency probably isn't the best plan of action

**Comment by joeyespo** [comment]
@asottile Makes sense! Yeah I wouldn't want to do it until I could dedicate more time to this. In any case, I appreciate the ask 😃
